src/spi_opdk.o.d:  \
 /home/water/workspace/WSN-Audio/Software/fpga/ecos/ecos-3.0/packages/devs/spi/sparc/opdk/v3_0/src/spi_opdk.c \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/devs_spi_sparc_leon3.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/devs_spi_sparc_opdk.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/infra/cyg_type.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/stddef.h \
  /opt/programs/XTOOLS/leon3/sparc-elf-3.4.4/bin/../lib/gcc/sparc-elf/3.4.4/include/stddef.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/basetype.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/infra/diag.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/infra.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/system.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/stdarg.h \
  /opt/programs/XTOOLS/leon3/sparc-elf-3.4.4/bin/../lib/gcc/sparc-elf/3.4.4/include/stdarg.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/error/errno.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/error.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/error/codes.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/io/devtab.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/io/io.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/hal.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/hal_sparc.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/hal_sparc_leon3.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/drv_api.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/kernel.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/kernel/kapi.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/memalloc/kapi.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/memalloc.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/kernel/kapidata.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_intr.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/vectors.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_xpic.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_io.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_smp.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_leon3.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_amba.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_clock.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/memalloc/kapidata.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_tables.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/hal/hal_arch.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/io/config_keys.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/io/spi.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/io/spi_leon3.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/io_spi.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/io/spi_opdk.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/string.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/isoinfra.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/error/strerror.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/libc/string/string.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/pkgconf/libc_string.h \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/libc/string/string.inl \
  /home/water/workspace/WSN-Audio/Software/fpga/wan/ecos/ecos_install/include/cyg/libc/string/bsdstring.h
