#ifndef CYGONCE_PKGCONF_SYSTEM_H
#define CYGONCE_PKGCONF_SYSTEM_H
/*
 * File <pkgconf/system.h>
 *
 * This file is generated automatically by the configuration
 * system. It should not be edited. Any changes to this file
 * may be overwritten.
 */

#define CYGNUM_VERSION_CURRENT 0x7fffff00
#define CYGPKG_HAL_SPARC v3_0
#define CYGPKG_HAL_SPARC_v3_0
#define CYGNUM_HAL_SPARC_VERSION_MAJOR 3
#define CYGNUM_HAL_SPARC_VERSION_MINOR 0
#define CYGNUM_HAL_SPARC_VERSION_RELEASE -1
#define CYGPKG_HAL_SPARC_LEON3 v3_0
#define CYGPKG_HAL_SPARC_LEON3_v3_0
#define CYGNUM_HAL_SPARC_LEON3_VERSION_MAJOR 3
#define CYGNUM_HAL_SPARC_LEON3_VERSION_MINOR 0
#define CYGNUM_HAL_SPARC_LEON3_VERSION_RELEASE -1
#define CYGBLD_HAL_TARGET_H   <pkgconf/hal_sparc.h>
#define CYGBLD_HAL_PLATFORM_H <pkgconf/hal_sparc_leon3.h>
#define CYG_HAL_STARTUP RAM
#define CYG_HAL_STARTUP_RAM
#define CYGHWR_MEMORY_LAYOUT_LDI <pkgconf/mlt_sparc_leon3_ram.ldi>
#define CYGHWR_MEMORY_LAYOUT_H <pkgconf/mlt_sparc_leon3_ram.h>
#define CYGPKG_HAL v3_0
#define CYGPKG_HAL_v3_0
#define CYGNUM_HAL_VERSION_MAJOR 3
#define CYGNUM_HAL_VERSION_MINOR 0
#define CYGNUM_HAL_VERSION_RELEASE -1
#define CYGPKG_IO v3_0
#define CYGPKG_IO_v3_0
#define CYGNUM_IO_VERSION_MAJOR 3
#define CYGNUM_IO_VERSION_MINOR 0
#define CYGNUM_IO_VERSION_RELEASE -1
#define CYGPKG_IO_SERIAL v3_0
#define CYGPKG_IO_SERIAL_v3_0
#define CYGNUM_IO_SERIAL_VERSION_MAJOR 3
#define CYGNUM_IO_SERIAL_VERSION_MINOR 0
#define CYGNUM_IO_SERIAL_VERSION_RELEASE -1
#define CYGPKG_INFRA v3_0
#define CYGPKG_INFRA_v3_0
#define CYGNUM_INFRA_VERSION_MAJOR 3
#define CYGNUM_INFRA_VERSION_MINOR 0
#define CYGNUM_INFRA_VERSION_RELEASE -1
#define CYGPKG_KERNEL v3_0
#define CYGPKG_KERNEL_v3_0
#define CYGNUM_KERNEL_VERSION_MAJOR 3
#define CYGNUM_KERNEL_VERSION_MINOR 0
#define CYGNUM_KERNEL_VERSION_RELEASE -1
#define CYGPKG_MEMALLOC v3_0
#define CYGPKG_MEMALLOC_v3_0
#define CYGNUM_MEMALLOC_VERSION_MAJOR 3
#define CYGNUM_MEMALLOC_VERSION_MINOR 0
#define CYGNUM_MEMALLOC_VERSION_RELEASE -1
#define CYGPKG_ISOINFRA v3_0
#define CYGPKG_ISOINFRA_v3_0
#define CYGNUM_ISOINFRA_VERSION_MAJOR 3
#define CYGNUM_ISOINFRA_VERSION_MINOR 0
#define CYGNUM_ISOINFRA_VERSION_RELEASE -1
#define CYGPKG_LIBC v3_0
#define CYGPKG_LIBC_v3_0
#define CYGNUM_LIBC_VERSION_MAJOR 3
#define CYGNUM_LIBC_VERSION_MINOR 0
#define CYGNUM_LIBC_VERSION_RELEASE -1
#define CYGPKG_LIBC_I18N v3_0
#define CYGPKG_LIBC_I18N_v3_0
#define CYGNUM_LIBC_I18N_VERSION_MAJOR 3
#define CYGNUM_LIBC_I18N_VERSION_MINOR 0
#define CYGNUM_LIBC_I18N_VERSION_RELEASE -1
#define CYGPKG_LIBC_SETJMP v3_0
#define CYGPKG_LIBC_SETJMP_v3_0
#define CYGNUM_LIBC_SETJMP_VERSION_MAJOR 3
#define CYGNUM_LIBC_SETJMP_VERSION_MINOR 0
#define CYGNUM_LIBC_SETJMP_VERSION_RELEASE -1
#define CYGPKG_LIBC_SIGNALS v3_0
#define CYGPKG_LIBC_SIGNALS_v3_0
#define CYGNUM_LIBC_SIGNALS_VERSION_MAJOR 3
#define CYGNUM_LIBC_SIGNALS_VERSION_MINOR 0
#define CYGNUM_LIBC_SIGNALS_VERSION_RELEASE -1
#define CYGPKG_LIBC_STARTUP v3_0
#define CYGPKG_LIBC_STARTUP_v3_0
#define CYGNUM_LIBC_STARTUP_VERSION_MAJOR 3
#define CYGNUM_LIBC_STARTUP_VERSION_MINOR 0
#define CYGNUM_LIBC_STARTUP_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDIO v3_0
#define CYGPKG_LIBC_STDIO_v3_0
#define CYGNUM_LIBC_STDIO_VERSION_MAJOR 3
#define CYGNUM_LIBC_STDIO_VERSION_MINOR 0
#define CYGNUM_LIBC_STDIO_VERSION_RELEASE -1
#define CYGPKG_LIBC_STDLIB v3_0
#define CYGPKG_LIBC_STDLIB_v3_0
#define CYGNUM_LIBC_STDLIB_VERSION_MAJOR 3
#define CYGNUM_LIBC_STDLIB_VERSION_MINOR 0
#define CYGNUM_LIBC_STDLIB_VERSION_RELEASE -1
#define CYGPKG_LIBC_STRING v3_0
#define CYGPKG_LIBC_STRING_v3_0
#define CYGNUM_LIBC_STRING_VERSION_MAJOR 3
#define CYGNUM_LIBC_STRING_VERSION_MINOR 0
#define CYGNUM_LIBC_STRING_VERSION_RELEASE -1
#define CYGPKG_LIBC_TIME v3_0
#define CYGPKG_LIBC_TIME_v3_0
#define CYGNUM_LIBC_TIME_VERSION_MAJOR 3
#define CYGNUM_LIBC_TIME_VERSION_MINOR 0
#define CYGNUM_LIBC_TIME_VERSION_RELEASE -1
#define CYGPKG_LIBM v3_0
#define CYGPKG_LIBM_v3_0
#define CYGNUM_LIBM_VERSION_MAJOR 3
#define CYGNUM_LIBM_VERSION_MINOR 0
#define CYGNUM_LIBM_VERSION_RELEASE -1
#define CYGPKG_IO_WALLCLOCK v3_0
#define CYGPKG_IO_WALLCLOCK_v3_0
#define CYGNUM_IO_WALLCLOCK_VERSION_MAJOR 3
#define CYGNUM_IO_WALLCLOCK_VERSION_MINOR 0
#define CYGNUM_IO_WALLCLOCK_VERSION_RELEASE -1
#define CYGPKG_ERROR v3_0
#define CYGPKG_ERROR_v3_0
#define CYGNUM_ERROR_VERSION_MAJOR 3
#define CYGNUM_ERROR_VERSION_MINOR 0
#define CYGNUM_ERROR_VERSION_RELEASE -1
#define CYGPKG_IO_SPI v3_0
#define CYGPKG_IO_SPI_v3_0
#define CYGNUM_IO_SPI_VERSION_MAJOR 3
#define CYGNUM_IO_SPI_VERSION_MINOR 0
#define CYGNUM_IO_SPI_VERSION_RELEASE -1

#endif
